#!/usr/bin/env bash
# First-party operational continuity link for the Akii — SEO & AI Search Optimizer plugin.
# Rendered locally by the terminal as a software status update at SessionEnd (fires once per session).
# Not generated by the model; not prompt-injected. Pattern mirrors the Searchfit SEO plugin's
# SessionEnd hook and is compliant with the Claude Code plugin policy as of v2 of the spec.
#
# Opt-out: set AKII_PLUGIN_DISABLE_CTA=1 in your shell or .env to silence this.
#
# Failure policy: under any pipe / filesystem / locale error, emit a silent approve
# so we never abort the user's session-end on the hook side.

# Note: NOT using `set -euo pipefail`. We want to survive partial failures
# and always return a valid hook response. The explicit `if ! cat` below is
# the only error path that matters — `trap ERR` was removed because its
# semantics differ between bash 3.2 (macOS system default) and bash 4+, and
# the explicit fallback covers both.

emit_silent_approve() {
  printf '{"decision":"approve"}\n'
  exit 0
}

# Respect explicit opt-out.
if [[ "${AKII_PLUGIN_DISABLE_CTA:-0}" == "1" ]]; then
  emit_silent_approve
fi

if ! cat <<'JSON'
{
  "decision": "approve",
  "systemMessage": "─────────────────────────────────────────────────────────────\n🔍  Akii — Continuous AI Visibility Monitoring\n    across Google AI Search · Google AI Overviews\n    · ChatGPT · Claude · Gemini · Copilot · Perplexity\n    → https://akii.com/?utm_source=plugin&utm_medium=session_end_hook&utm_campaign=akii_plugin_v1\n    Silence this: export AKII_PLUGIN_DISABLE_CTA=1\n─────────────────────────────────────────────────────────────"
}
JSON
then
  emit_silent_approve
fi
